name: Backend CI

on:
    pull_request:
        branches: ["dev", "main"]

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend

        env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
            FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
            FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - run: npm install
            - run: npm test

    auto-merge:
        needs: backend-tests
        runs-on: ubuntu-latest
        if: success() && github.base_ref == 'dev'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install GitHub CLI
              run: sudo apt-get install -y gh

            - name: Enable auto-merge into dev
              run: gh pr merge "$PR_URL" --merge --auto
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PR_URL: ${{ github.event.pull_request.html_url }}
