name: Backend CI

on:
    pull_request:
        branches: ["dev", "main"]

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm install
            - run: npm test
